import React, { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string, params?: Record<string, string>) => string;
}

const translations = {
  en: {
    'nav.free-delivery': 'Free delivery on orders over {{price}}',
    'nav.categories': 'Categories',
    'nav.deals': 'Deals',
    'nav.whats-new': "What's New",
    'nav.delivery': 'Delivery',
    'nav.search': 'Search Product',
    'nav.account': 'Account',
    'nav.cart': 'Cart',
    'hero.title': 'Shopping And Department Store.',
    'hero.desc': 'Shopping is a bit of a relaxing hobby for me, which is sometimes troubling for the bank balance.',
    'hero.learn': 'Learn More',
    'cat.title': 'Shop Our Top Categories',
    'banner.title': 'Grab Upto 50% Off On Selected Headphone',
    'banner.buy': 'Buy Now',
    'products.for-you': 'Latest News',
    'products.add': 'Add to Cart',
    'products.sort': 'Sort by',
    'services.title': 'Services To Help You Shop',
    'detail.back-electronics': 'Electronics',
    'detail.back-audio': 'Audio',
    'detail.back-headphones': 'Headphones',
    'detail.or-month': 'or 99.99/month',
    'detail.financing': 'Suggested payments with 6 months special financing',
    'detail.choose-color': 'Choose a Color',
    'detail.left': 'Only 12 Items Left!',
    'detail.dont-miss': "Don't miss it",
    'detail.buy-now': 'Buy Now',
    'detail.free-delivery': 'Free Delivery',
    'detail.free-delivery-desc': 'Enter your Postal code for Delivery Availability',
    'detail.return': 'Return Delivery',
    'detail.return-desc': 'Free 30days Delivery Returns. Details',
    'detail.specs': 'Full Specifications',
    'checkout.title': 'Checkout',
    'checkout.review': 'Review Item And Shipping',
    'checkout.delivery': 'Delivery Information',
    'checkout.edit': 'Edit Information',
    'checkout.summary': 'Order Summary',
    'checkout.coupon': 'Enter Coupon Code',
    'checkout.apply': 'Apply Coupon',
    'checkout.payment': 'Payment Details',
    'checkout.pay': 'Pay',
    'checkout.success': 'Your order has been accepted',
    'checkout.continue': 'Continue Shopping',
    'footer.about': 'About Us',
    'footer.support': 'Support',
    'footer.policy': 'Policy',
    'footer.contact': 'Contact Us',
    'cat.smartphones': 'Smartphones',
    'cat.computers': 'Computers',
    'cat.tablets': 'Tablets',
    'cat.headphones': 'Headphones',
    'cat.earphones': 'Earphones',
    'cat.smartwatches': 'Smartwatches',
    'feature.title-1': 'Your Favorite Brands,',
    'feature.title-2': 'All in One Place.',
    'feature.desc': "We partner with the world's leading tech manufacturers to bring you original products with official warranties. From high-end laptops to the latest smartphones.",
    'feature.explore': 'Explore Brands',
    'feature.learn': 'Learn more',
    'feature.shop-now': 'Shop now',
    'testimonials.title': 'Community Voices',
    'testimonials.subtitle': 'Discover how G&C Tech is changing the game for tech enthusiasts around the world.',
    'testimonials.1.name': 'Sarah Johnson',
    'testimonials.1.role': 'Tech Enthusiast',
    'testimonials.1.quote': 'The delivery was incredibly fast, and the packaging was premium. Best shopping experience ever.',
    'testimonials.1.initials': 'SJ',
    'testimonials.2.name': 'Marc Dubois',
    'testimonials.2.role': 'Professional Gamer',
    'testimonials.2.quote': 'G&C Tech has the best selection of gaming peripherals. I found exactly what I needed for my setup.',
    'testimonials.2.initials': 'MD',
    'testimonials.3.name': 'Elena Rodriguez',
    'testimonials.3.role': 'UI/UX Designer',
    'testimonials.3.quote': 'The interface is so clean and easy to use. I love the minimalist aesthetic and the curation.',
    'testimonials.3.initials': 'ER',
    'testimonials.stat.verified': 'Verified Buyer',
    'testimonials.stat.delivery': 'Fast Delivery',
    'testimonials.tag.featured': 'Featured',
    'testimonials.tag.tech': 'Tech',
    'newsletter.title': 'Join our newsletter',
    'newsletter.subtitle': 'Get 20% off your first order plus early access to new drops and secret sales.',
    'newsletter.placeholder': 'Enter your email',
    'newsletter.button': 'Subscribe',
    'newsletter.success': 'Thanks for subscribing!',
    'newsletter.privacy': 'By subscribing, you agree to our Privacy Policy and Terms of Service.',
    'auth.login.title': 'Welcome back',
    'auth.login.subtitle': 'Enter your details to access your account',
    'auth.login.email': 'Email address',
    'auth.login.password': 'Password',
    'auth.login.forgot': 'Forgot password?',
    'auth.login.submit': 'Sign In',
    'auth.login.no-account': "Don't have an account?",
    'auth.login.signup': 'Sign Up',
    'auth.signup.title': 'Create account',
    'auth.signup.subtitle': 'Join G&C Tech today and start shopping',
    'auth.signup.fullname': 'Full Name',
    'auth.signup.submit': 'Create Account',
    'auth.signup.have-account': 'Already have an account?',
    'auth.signup.login': 'Sign In',
    'auth.google': 'Continue with Google',
    'auth.or': 'or',
    'legal.privacy.title': 'Privacy Policy',
    'legal.terms.title': 'Terms of Service',
    'legal.refund.title': 'Refund Policy',
    'legal.last-updated': 'Last Updated:',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',
    'footer.refund': 'Refund Policy',
    'cart.title': 'Shopping Cart',
    'cart.empty': 'Your cart is empty',
    'cart.continue': 'Continue Shopping',
    'cart.summary': 'Order Summary',
    'cart.subtotal': 'Subtotal',
    'cart.shipping': 'Shipping',
    'cart.tax': 'Tax',
    'cart.total': 'Total',
    'cart.checkout': 'Proceed to Checkout',
    'cart.remove': 'Remove',
    'cart.items': 'items',
    'cart.step1': 'Cart',
    'cart.step2': 'Delivery',
    'cart.step3': 'Payment',
    'cart.validate': 'Validate Cart',
    'cart.next': 'Next Step',
    'cart.prev': 'Previous Step',
    'delivery.zone': 'Delivery Zone',
    'delivery.zone.placeholder': 'Select your zone',
    'delivery.details': 'Delivery Details',
    'delivery.details.placeholder': 'Apt, Floor, landmark...',
    'delivery.phone': 'Phone Number',
    'delivery.date': 'Delivery Date',
    'delivery.time': 'Time Slot',
    'delivery.payment': 'Payment Method',
    'delivery.payment.momo': 'Mobile Money (Momo)',
    'delivery.payment.cash': 'Cash on Delivery',
    'delivery.payment.whatsapp': 'Order and pay on WhatsApp',
    'delivery.payment.whatsapp.desc': 'We will generate a dynamic message with your order details so you can finalize payment with us on WhatsApp.',
    'delivery.whatsapp.not-opened': "Didn't redirect automatically? Click here to start WhatsApp",
    'delivery.confirm': 'Confirm Order',
    'smartphones.title': 'Smartphones',
    'smartphones.subtitle': 'Discover the latest mobile devices with advanced cameras and powerful performance.',
    'computers.title': 'Computers & Laptops',
    'computers.subtitle': 'Powerful workstations and portable laptops for work, play, and everything in between.',
    'tablets.title': 'Tablets',
    'tablets.subtitle': 'The perfect balance of power and portability for your daily tasks and entertainment.',
    'headphones.title': 'Headphones',
    'headphones.subtitle': 'Immerse yourself in high-fidelity sound with our premium selection of over-ear headphones.',
    'earphones.title': 'Earphones',
    'earphones.subtitle': 'Compact, wireless, and powerful. Enjoy your music on the go with crystal clear audio.',
    'smartwatches.title': 'Smartwatches',
    'smartwatches.subtitle': 'Stay connected and track your health with the latest in wearable technology.',
    'support.help.title': 'Help Center',
    'support.help.subtitle': 'Find answers to your questions and learn how to make the most of your experience.',
    'support.shipping.title': 'Shipping Information',
    'support.shipping.subtitle': 'Everything you need to know about how we deliver your favorite electronics.',
    'support.contact.title': 'Contact Us',
    'support.contact.subtitle': 'We\'re here to help. Reach out to us through any of our channels.',
    'breadcrumb.home': 'Home',
    'breadcrumb.electronics': 'Electronics',
    'breadcrumb.smartphones': 'Smartphones',
    'breadcrumb.computers': 'Computers',
    'breadcrumb.tablets': 'Tablets',
    'breadcrumb.headphones': 'Headphones',
    'breadcrumb.earphones': 'Earphones',
    'breadcrumb.smartwatches': 'Smartwatches',
    'nav.call-us': 'Call Us',
    'nav.location': 'Location',
    'nav.help': 'Help',
    'nav.shop-now': 'Shop now',
    'nav.popular': 'Popular Categories',
    'nav.items-available': '240 items available',
    'nav.no-results': 'No products found for "{{query}}"',
    'nav.menu': 'Menu',
    'nav.contact-support': 'Contact Support',
    'nav.login': 'Log In',
    'footer.desc': 'We offer the best electronics at the most competitive prices. Quality and customer satisfaction guaranteed.',
    'footer.story': 'Our Story',
    'footer.careers': 'Careers',
    'footer.press': 'Press',
    'footer.blog': 'Blog',
    'footer.help-center': 'Help Center',
    'footer.returns': 'Returns',
    'footer.shipping-info': 'Shipping Info',
    'footer.contact-us': 'Contact Us',
    'footer.rights': 'All rights reserved.',
    'filter.brand': 'Brand',
    'filter.all': 'All Filters',
    'filter.sort': 'Sort by',
    'products.load-more': 'Load More Products',
    'cart.contact-number': 'Contact Number',
    'cart.no-details': 'No extra details',
    'cart.secure': 'Secure transaction protected'
  },
  fr: {
    'nav.free-delivery': 'Livraison gratuite dès {{price}} d\'achat',
    'nav.categories': 'Catégories',
    'nav.deals': 'Offres',
    'nav.whats-new': 'Nouveautés',
    'nav.delivery': 'Livraison',
    'nav.search': 'Rechercher un produit',
    'nav.account': 'Compte',
    'nav.cart': 'Panier',
    'hero.title': 'Boutique et Grand Magasin.',
    'hero.desc': 'Le shopping est un passe-temps relaxant pour moi, ce qui est parfois gênant pour le solde bancaire.',
    'hero.learn': 'En savoir plus',
    'cat.title': 'Nos meilleures catégories',
    'banner.title': "Jusqu'à 50% de réduction sur une sélection de casques",
    'banner.buy': 'Acheter maintenant',
    'products.for-you': 'Dernières nouveautés',
    'products.add': 'Ajouter au panier',
    'products.sort': 'Trier par',
    'services.title': 'Des services pour vous aider',
    'detail.back-electronics': 'Électronique',
    'detail.back-audio': 'Audio',
    'detail.back-headphones': 'Casques',
    'detail.or-month': 'ou 99,99/mois',
    'detail.financing': 'Paiements suggérés avec financement spécial de 6 mois',
    'detail.choose-color': 'Choisissez une couleur',
    'detail.left': 'Plus que 12 articles !',
    'detail.dont-miss': 'Ne le ratez pas',
    'detail.buy-now': 'Acheter maintenant',
    'detail.free-delivery': 'Livraison gratuite',
    'detail.free-delivery-desc': 'Entrez votre code postal pour la disponibilité',
    'detail.return': 'Retour gratuit',
    'detail.return-desc': 'Retours gratuits sous 30 jours. Détails',
    'detail.specs': 'Spécifications complètes',
    'checkout.title': 'Paiement',
    'checkout.review': 'Vérifier l\'article et l\'expédition',
    'checkout.delivery': 'Informations de livraison',
    'checkout.edit': 'Modifier les informations',
    'checkout.summary': 'Résumé de la commande',
    'checkout.coupon': 'Code promo',
    'checkout.apply': 'Appliquer',
    'checkout.payment': 'Détails du paiement',
    'checkout.pay': 'Payer',
    'checkout.success': 'Votre commande a été acceptée',
    'checkout.continue': 'Continuer vos achats',
    'footer.about': 'À propos',
    'footer.support': 'Support',
    'footer.policy': 'Politique',
    'footer.contact': 'Contactez-nous',
    'cat.smartphones': 'Smartphones',
    'cat.computers': 'Ordinateurs',
    'cat.tablets': 'Tablettes',
    'cat.headphones': 'Casques',
    'cat.earphones': 'Écouteurs',
    'cat.smartwatches': 'Montres connectées',
    'feature.title-1': 'Vos marques préférées,',
    'feature.title-2': 'Toutes au même endroit.',
    'feature.desc': "Nous sommes partenaires des plus grands fabricants technologiques mondiaux pour vous proposer des produits originaux avec des garanties officielles. Des ordinateurs portables haut de gamme aux derniers smartphones.",
    'feature.explore': 'Explorer les marques',
    'feature.learn': 'En savoir plus',
    'feature.shop-now': 'Acheter maintenant',
    'testimonials.title': 'Voix de la Communauté',
    'testimonials.subtitle': 'Découvrez comment G&C Tech change la donne pour les passionnés de technologie à travers le monde.',
    'testimonials.1.name': 'Léa Martin',
    'testimonials.1.role': 'Fan de Tech',
    'testimonials.1.quote': 'La livraison a été incroyablement rapide et l\'emballage était premium. La meilleure expérience d\'achat à ce jour.',
    'testimonials.1.initials': 'LM',
    'testimonials.2.name': 'Marc Dubois',
    'testimonials.2.role': 'Gamer Professionnel',
    'testimonials.2.quote': 'G&C Tech a la meilleure sélection de périphériques gaming. J\'ai trouvé exactement ce qu\'il me fallait pour mon setup.',
    'testimonials.2.initials': 'MD',
    'testimonials.3.name': 'Hélène Lefebvre',
    'testimonials.3.role': 'Designer UI/UX',
    'testimonials.3.quote': 'L\'interface est tellement propre et facile à utiliser. J\'adore l\'esthétique minimaliste et la sélection.',
    'testimonials.3.initials': 'HL',
    'testimonials.stat.verified': 'Acheteur Vérifié',
    'testimonials.stat.delivery': 'Livraison Rapide',
    'testimonials.tag.featured': 'En vedette',
    'testimonials.tag.tech': 'Tech',
    'newsletter.title': 'Rejoignez notre newsletter',
    'newsletter.subtitle': 'Bénéficiez de 20% de réduction sur votre première commande et d\'un accès anticipé aux nouveautés.',
    'newsletter.placeholder': 'Entrez votre email',
    'newsletter.button': 'S\'abonner',
    'newsletter.success': 'Merci pour votre abonnement !',
    'newsletter.privacy': 'En vous abonnant, vous acceptez notre politique de confidentialité et nos conditions d\'utilisation.',
    'auth.login.title': 'Bon retour',
    'auth.login.subtitle': 'Entrez vos informations pour accéder à votre compte',
    'auth.login.email': 'Adresse e-mail',
    'auth.login.password': 'Mot de passe',
    'auth.login.forgot': 'Mot de passe oublié ?',
    'auth.login.submit': 'Se connecter',
    'auth.login.no-account': "Vous n'avez pas de compte ?",
    'auth.login.signup': 'S\'inscrire',
    'auth.signup.title': 'Créer un compte',
    'auth.signup.subtitle': 'Rejoignez G&C Tech dès aujourd\'hui',
    'auth.signup.fullname': 'Nom complet',
    'auth.signup.submit': 'Créer le compte',
    'auth.signup.have-account': 'Vous avez déjà un compte ?',
    'auth.signup.login': 'Se connecter',
    'auth.google': 'Continuer avec Google',
    'auth.or': 'ou',
    'legal.privacy.title': 'Politique de Confidentialité',
    'legal.terms.title': 'Conditions d\'Utilisation',
    'legal.refund.title': 'Politique de Remboursement',
    'legal.last-updated': 'Dernière mise à jour :',
    'footer.privacy': 'Politique de Confidentialité',
    'footer.terms': 'Conditions d\'Utilisation',
    'footer.refund': 'Politique de Remboursement',
    'cart.title': 'Panier',
    'cart.empty': 'Votre panier est vide',
    'cart.continue': 'Continuer mes achats',
    'cart.summary': 'Résumé de la commande',
    'cart.subtotal': 'Sous-total',
    'cart.shipping': 'Livraison',
    'cart.tax': 'Taxes',
    'cart.total': 'Total',
    'cart.checkout': 'Passer à la caisse',
    'cart.remove': 'Supprimer',
    'cart.items': 'articles',
    'cart.step1': 'Panier',
    'cart.step2': 'Livraison',
    'cart.step3': 'Paiement',
    'cart.validate': 'Valider le panier',
    'cart.next': 'Étape suivante',
    'cart.prev': 'Étape précédente',
    'delivery.zone': 'Zone de livraison',
    'delivery.zone.placeholder': 'Sélectionnez votre zone',
    'delivery.details': 'Détails de livraison',
    'delivery.details.placeholder': 'Appartement, étage, point de repère...',
    'delivery.phone': 'Numéro de téléphone',
    'delivery.date': 'Date de livraison',
    'delivery.time': 'Plage horaire',
    'delivery.payment': 'Mode de paiement',
    'delivery.payment.momo': 'Mobile Money (Momo)',
    'delivery.payment.cash': 'Espèces à la livraison',
    'delivery.payment.whatsapp': 'Commander et payer sur WhatsApp',
    'delivery.payment.whatsapp.desc': 'Nous générerons un message personnalisé récapitulant votre panier afin de finaliser le paiement avec nous directement par WhatsApp.',
    'delivery.whatsapp.not-opened': "WhatsApp ne s'est pas ouvert automatiquement ? Cliquez ici pour lancer la conversation",
    'delivery.confirm': 'Confirmer la commande',
    'smartphones.title': 'Smartphones',
    'smartphones.subtitle': 'Découvrez les derniers appareils mobiles avec des caméras avancées et des performances puissantes.',
    'computers.title': 'Ordinateurs',
    'computers.subtitle': 'Des stations de travail puissantes et des ordinateurs portables pour le travail et le divertissement.',
    'tablets.title': 'Tablettes',
    'tablets.subtitle': 'L\'équilibre parfait entre puissance et portabilité pour vos tâches quotidiennes.',
    'headphones.title': 'Casques',
    'headphones.subtitle': 'Immergez-vous dans un son haute fidélité avec notre sélection de casques premium.',
    'earphones.title': 'Écouteurs',
    'earphones.subtitle': 'Compacts, sans fil et puissants. Profitez de votre musique partout avec un son cristallin.',
    'smartwatches.title': 'Montres Connectées',
    'smartwatches.subtitle': 'Restez connecté et suivez votre santé avec les dernières technologies portables.',
    'support.help.title': 'Centre d\'Aide',
    'support.help.subtitle': 'Trouvez des réponses à vos questions et apprenez à tirer le meilleur parti de votre expérience.',
    'support.shipping.title': 'Informations de Livraison',
    'support.shipping.subtitle': 'Tout ce que vous devez savoir sur la façon dont nous livrons vos produits préférés.',
    'support.contact.title': 'Contactez-nous',
    'support.contact.subtitle': 'Nous sommes là pour vous aider. Contactez-nous via l\'un de nos canaux.',
    'breadcrumb.home': 'Accueil',
    'breadcrumb.electronics': 'Électronique',
    'breadcrumb.smartphones': 'Smartphones',
    'breadcrumb.computers': 'Ordinateurs',
    'breadcrumb.tablets': 'Tablettes',
    'breadcrumb.headphones': 'Casques',
    'breadcrumb.earphones': 'Écouteurs',
    'breadcrumb.smartwatches': 'Montres',
    'nav.call-us': 'Appelez-nous',
    'nav.location': 'Localisation',
    'nav.help': 'Aide',
    'nav.shop-now': 'Acheter',
    'nav.popular': 'Catégories populaires',
    'nav.items-available': '240 articles disponibles',
    'nav.no-results': 'Aucun produit trouvé pour "{{query}}"',
    'nav.menu': 'Menu',
    'nav.contact-support': 'Contacter le support',
    'nav.login': 'Se connecter',
    'footer.desc': 'Nous proposons les meilleurs appareils électroniques aux prix les plus compétitifs. Qualité et satisfaction client garanties.',
    'footer.story': 'Notre histoire',
    'footer.careers': 'Carrières',
    'footer.press': 'Presse',
    'footer.blog': 'Blog',
    'footer.help-center': "Centre d'aide",
    'footer.returns': 'Retours',
    'footer.shipping-info': 'Infos livraison',
    'footer.contact-us': 'Contactez-nous',
    'footer.rights': 'Tous droits réservés.',
    'filter.brand': 'Marque',
    'filter.all': 'Tous les filtres',
    'filter.sort': 'Trier par',
    'products.load-more': 'Voir plus de produits',
    'cart.contact-number': 'Numéro de contact',
    'cart.no-details': 'Aucun détail supplémentaire',
    'cart.secure': 'Transaction sécurisée'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string, params?: Record<string, string>) => {
    let translation = translations[language][key as keyof typeof translations['en']] || key;
    
    if (params) {
      Object.entries(params).forEach(([k, v]) => {
        translation = translation.replace(`{{${k}}}`, v);
      });
    }
    
    return translation;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) throw new Error('useLanguage must be used within a LanguageProvider');
  return context;
}
